app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")

app$setInputs(searchText = "Mandarin Duck")
app$setInputs(searchText = "Eurasian Red Squirrel")
app$setInputs(searchText = "Northern Crested Newt")
app$setInputs(searchText = "Northern Bullfinch")
app$setInputs(searchText = "")
app$setInputs(searchText = "Aix galericulata")
app$snapshot()
app$setInputs(searchText = "Northern Bullfinch")
app$snapshot()
app$setInputs(searchText = "Brown Bear")
app$snapshot()
